### ISSUE TITLE
Is 'Jump Start Sass' still a current resource?

### ISSUE THREAD

**Issue by travisricks** [KittyGiraudel/ama#116]
Hi Kitty,
I have been wanting to get more into learning about writing mixins and using functions for Sass so I was thinking about getting this book. Basically I'd like to move on from just using Sass to include separate files, use variables and nesting. 

I noticed though that the book is about five years old now, so I just wanted to check and see if it should still be considered a current resource for Sass? (I just know that languages seem to change so rapidly, I just wanted to make sure this was still current before purchasing it.)

p.s. I love your content! Your tweets, website, sass guidelines, etc. are all so helpful and motivating for me as a newer developer. Thank you for everything you do for the community!

**Comment by KittyGiraudel** [comment]
Good morning Travis,

Thank you for the kind words, that means a lot. I really appreciate it. 😊

In my opinion, Jump Start Sass still a pretty good introduction to all the features from the language. Sass has not evolved _that_ much over the last few years and I would expect most of the content to be quite accurate. I think the main thing that’s going to be missing is dependency management (anything about the [`@use`](https://sass-lang.com/documentation/at-rules/use) and the [`@forward`](https://sass-lang.com/documentation/at-rules/forward) annotations). Back then, it was still common to `@import` all partials into a main file (which is how I recommended doing things in [Sass Guidelines](https://sass-guidelin.es/#architecture)).

But everything else, from variables to mixins, from conditions to loops, from functions to warnings, everything should be very valid and still applicable, so I would say it’s probably worth a read to be more familiar with the language.

If you do buy it and read it though, I’d love to know if there are things you found outdated or not applicable anymore. Maybe I could check with Learnable if they want to update it. ;)

**Comment by travisricks** [comment]
Thank you for the information and the quick reply. I think I'll give it a read this weekend. (I'll put that 'Sass in a weekend' title to the test lol)

I'll let you know if anything seems outdated to me.

Have a great day!
