### ISSUE TITLE
SASS guidelines class_convention rule?

### ISSUE THREAD

**Issue by x4th** [KittyGiraudel/ama#120]
Hey, first of all, thank you for all the work you've done.

I'm wondering about the class naming convention rule you've mentioned in https://sass-guidelin.es/#scss-lint. Can you point me to a place where it's elaborated on or provide a few examples?

**Comment by KittyGiraudel** [comment]
Hello and thank you for the kind words. I’m pretty sure I haven’t authored the SCSS-Lint configuration and took it from somewhere else. In any case, I believe the regular expression used for `class_convention` is issued from SMACSS and/or Inuit CSS. :)

**Comment by x4th** [comment]
Thanks for the response, I'll check both of those out. :)
