### ISSUE TITLE
May 2022 layoff

### ISSUE THREAD

**Issue by mauryakrishna** [KittyGiraudel/ama#122]
I read your longer version of resume and learned that you you been the first engineer in Gorillas.
Build the team and led it.

But still you were let go. 

What though do you have with this happening? As being the older person at company regarded as safe in term of employment and also the highly rewarding whether personally or financially.

**Comment by KittyGiraudel** [comment]
Hello. :)

There is only so much I can discuss publicly as you can imagine. For sure, it is uncomfortable being let go, especially as someone who was there early on and contributed to building the Product & Engineering department from the ground-up. It certainly leaves a bit of a bitter taste, but I appreciate being able to look back on the last 18 months and feel proud and happy of what we‘ve built.

Fortunately for me, I happen to be very privileged, and already have a relatively long career behind me, which puts me in a comfortable position to find my next role. So while it assuredly sucks, I’ll bounce back relatively rapidly (hopefully that is).

**Comment by krishnamauryaext** [comment]
Since you were one of the early engineers. Did you get the benefit of joining an early stage companies? Like, in terms of compensation, role and responsibility, an opportunity to make an impact.

**Comment by KittyGiraudel** [comment]
Certainly! I was the second engineer to join the company, at a time where our department was essentially 5 people (short of 200 nowadays)? It was very rewarding to be there that early on. There was everything to build, both technically and culturally. It was challenging and a lot of fun. :)

**Comment by mauryakrishna** [comment]
I found you through the job announcement tweet. Is this way of attracting the recruiters/great opportunities working for you?

**Comment by mauryakrishna** [comment]
What mistakes did you made? That given the rewind button you would like to correct/avoid?

**Comment by KittyGiraudel** [comment]
Tough one! I don’t know if there is something in particular I would say was a mistake.

I think starting with a homemade solution for the new internal tools platform might have been a debatable decision? A framework àla Next.js would have been plain enough and made things easier in the long run. Right now, there is a project to move it to Next.js which might never be picked up. Bit of a shame, I should have thought about it more.

**Comment by mauryakrishna** [comment]
Recently, I read about Atomic design systems at https://atomicdesign.bradfrost.com/. It did covered the details about the need of the terminology, benefits and impact. But no specific pointers on how one can get started learning it.

Would you like to recommend some resources on building frontend design systems?

**Comment by KittyGiraudel** [comment]
Unfortunately design systems were never my forte, so I’m not the best person to ask. ;)
