### ISSUE TITLE
Searching for a mission based team?

### ISSUE THREAD

**Issue by tn819** [KittyGiraudel/ama#123]
Hi Kitty,

I'm really impressed reading through your blog on accessibility work. Also love the communication of your leadership style + documentation focus. I barely am scratching at the surface of this field. However, my fav is the Simplified Javascript jargon... that is bookmarked

I'm looking for really skilled devs to join me on a greenfield project on an important issue: climate change

I think we present an interesting challenge to automate + improve the carbon offset market. Our founder team is super experienced having led Product organizations, founded multiple times and directed one of the world's largest sustainability funds. Read more here: https://www.bluelayer.io/mission. 

Would you be open to a chat?

**Comment by KittyGiraudel** [comment]
Hello Thomas. Please reach out on LinkedIn for any job prospect. :)
